language: cpp
compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq lcov
#  - sudo apt-get install -qq libxml2-utils
#  - sudo apt-get install -qq xsltproc
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script: ./build-all.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)


notifications:
   email: false
