#pragma once

#include <innodb/univ/univ.h>

/** Latching order levels. If you modify these, you have to also update
LatchDebug internals in sync0debug.cc */

enum latch_level_t {
  SYNC_UNKNOWN = 0,

  SYNC_MUTEX = 1,

  RW_LOCK_SX,
  RW_LOCK_X_WAIT,
  RW_LOCK_S,
  RW_LOCK_X,
  RW_LOCK_NOT_LOCKED,

  SYNC_LOCK_FREE_HASH,

  SYNC_MONITOR_MUTEX,

  SYNC_ANY_LATCH,

  SYNC_FIL_SHARD,

  SYNC_DOUBLEWRITE,

  SYNC_PAGE_ARCH_OPER,

  SYNC_BUF_FLUSH_LIST,
  SYNC_BUF_FLUSH_STATE,
  SYNC_BUF_ZIP_HASH,
  SYNC_BUF_FREE_LIST,
  SYNC_BUF_ZIP_FREE,
  SYNC_BUF_BLOCK,
  SYNC_BUF_PAGE_HASH,
  SYNC_BUF_LRU_LIST,
  SYNC_BUF_CHUNKS,

  SYNC_POOL,
  SYNC_POOL_MANAGER,

  SYNC_SEARCH_SYS,

  SYNC_WORK_QUEUE,

  SYNC_FTS_TOKENIZE,
  SYNC_FTS_OPTIMIZE,
  SYNC_FTS_BG_THREADS,
  SYNC_FTS_CACHE_INIT,
  SYNC_RECV,

  SYNC_LOG_WRITER,
  SYNC_LOG_WRITE_NOTIFIER,
  SYNC_LOG_FLUSH_NOTIFIER,
  SYNC_LOG_FLUSHER,
  SYNC_LOG_CLOSER,
  SYNC_LOG_CHECKPOINTER,
  SYNC_LOG_SN,
  SYNC_PAGE_ARCH,
  SYNC_PAGE_ARCH_CLIENT,
  SYNC_LOG_ARCH,

  SYNC_PAGE_CLEANER,
  SYNC_PURGE_QUEUE,
  SYNC_TRX_SYS_HEADER,
  SYNC_REC_LOCK,
  SYNC_THREADS,
  SYNC_TRX,
  SYNC_TRX_SYS,
  SYNC_LOCK_SYS,
  SYNC_LOCK_WAIT_SYS,

  SYNC_INDEX_ONLINE_LOG,

  SYNC_IBUF_BITMAP,
  SYNC_IBUF_BITMAP_MUTEX,
  SYNC_IBUF_TREE_NODE,
  SYNC_IBUF_TREE_NODE_NEW,
  SYNC_IBUF_INDEX_TREE,

  SYNC_IBUF_MUTEX,

  SYNC_FSP_PAGE,
  SYNC_FSP,
  SYNC_TEMP_POOL_MANAGER,
  SYNC_EXTERN_STORAGE,
  SYNC_RSEG_ARRAY_HEADER,
  SYNC_TRX_UNDO_PAGE,
  SYNC_RSEG_HEADER,
  SYNC_RSEG_HEADER_NEW,
  SYNC_TEMP_SPACE_RSEG,
  SYNC_UNDO_SPACE_RSEG,
  SYNC_TRX_SYS_RSEG,
  SYNC_TRX_UNDO,
  SYNC_PURGE_LATCH,
  SYNC_TREE_NODE,
  SYNC_TREE_NODE_FROM_HASH,
  SYNC_TREE_NODE_NEW,
  SYNC_INDEX_TREE,
  SYNC_RSEGS,
  SYNC_UNDO_SPACES,

  SYNC_PERSIST_DIRTY_TABLES,
  SYNC_PERSIST_AUTOINC,

  SYNC_IBUF_PESS_INSERT_MUTEX,
  SYNC_IBUF_HEADER,
  SYNC_DICT_HEADER,
  SYNC_TABLE,
  SYNC_STATS_AUTO_RECALC,
  SYNC_DICT_AUTOINC_MUTEX,
  SYNC_DICT,
  SYNC_PARSER,
  SYNC_FTS_CACHE,
  SYNC_UNDO_DDL,

  SYNC_DICT_OPERATION,

  SYNC_TRX_I_S_LAST_READ,

  SYNC_TRX_I_S_RWLOCK,

  SYNC_RECV_WRITER,

  /** Level is varying. Only used with buffer pool page locks, which
  do not have a fixed level, but instead have their level set after
  the page is locked; see e.g.  ibuf_bitmap_get_map_page(). */

  SYNC_LEVEL_VARYING,

  /** This can be used to suppress order checking. */
  SYNC_NO_ORDER_CHECK,

  /** Maximum level value */
  SYNC_LEVEL_MAX = SYNC_NO_ORDER_CHECK
};
